server:
  port: 8080

spring:
  # 配置数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devin?currentSchema=other
    username: devin
    password: wzh7230610

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

sso:
  saml:
    idp-url: http://localhost:14008
    idp-entity-id: http://localhost:14008/login/saml/authorize/admin/Demo
    entity-id: http://localhost:8080
    acs-url: http://localhost:8080/sso/saml/callback
  oauth2:
    client-id: 410b171f1454f505bf7482e9f15d52c717b33e37f42d1d43a10c735e233b4989
    client-secret: 5c0a1dc6784ca0b8f3f473c8ea8a35819b6cca21c6b34fcaa0695457bf49982f
    redirect-url: http://localhost:8080/sso/oauth/callback
    home-url: http://localhost:8080
    scope: profile email address phone
    idPUrl: http://localhost:14008/.well-known/openid-configuration
  azure-adfs:
    # Azure ADFS 租户 ID (需要替换为实际的租户 ID)
    tenant-id: your-tenant-id
    # Azure ADFS 应用程序（客户端）ID (需要替换为实际的客户端 ID)
    client-id: your-client-id
    # Azure ADFS 客户端密钥 (需要替换为实际的客户端密钥)
    client-secret: your-client-secret
    # 重定向 URI
    redirect-uri: http://localhost:8080/sso/azure-adfs/callback
    # 作用域
    scope: openid profile email
    # Azure ADFS 实例 URL (需要替换为实际的 ADFS 服务器 URL)
    # 格式: https://your-adfs-server/adfs
    authority: https://your-adfs-server/adfs
    # 登录成功后的主页 URL
    home-url: http://localhost:8080